import {createHash,randomBytes,timingSafeEqual} from 'node:crypto';
import type {Settings} from '@/server/config/llm-models';
import {getDb} from '@/db';
const COOKIE='cover_letter_admin';
export async function isAdministrator(request:Request,settings:Settings){const token=cookieValue(request.headers.get('cookie')||'',COOKIE);if(!token)return false;const id=hash(token);const row=getDb().prepare('SELECT login,expires_at FROM admin_sessions WHERE id=?').get(id) as {login:string;expires_at:number}|undefined;if(!row||row.expires_at<=Date.now()||row.login!==settings.ADMIN_LOGIN){if(row)getDb().prepare('DELETE FROM admin_sessions WHERE id=?').run(id);return false;}return true;}
export async function verifyAdminCredentials(login:string,password:string,settings:Settings){if(!settings.ADMIN_LOGIN||login!==settings.ADMIN_LOGIN||!settings.ADMIN_PASSWORD_HASH)return false;const [iterationsText,salt,expected]=settings.ADMIN_PASSWORD_HASH.split(':');const iterations=Number(iterationsText);if(!Number.isInteger(iterations)||iterations<100000||!salt||!expected)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:Buffer.from(salt,'base64url'),iterations},key,256);return safeEqual(Buffer.from(bits).toString('base64url'),expected);}
export async function createAdminCookie(settings:Settings){if(!settings.ADMIN_LOGIN)throw new Error('Административный вход не настроен.');const ttl=Math.max(1,Number(settings.SESSION_TTL_MINUTES)||720)*60000;const max=Math.max(1,Number(settings.MAX_SESSIONS)||5);const db=getDb();const token=randomBytes(32).toString('base64url');const now=Date.now();db.prepare('DELETE FROM admin_sessions WHERE expires_at<=?').run(now);db.prepare('INSERT INTO admin_sessions(id,login,expires_at,created_at) VALUES(?,?,?,?)').run(hash(token),settings.ADMIN_LOGIN,now+ttl,now);db.prepare('DELETE FROM admin_sessions WHERE id IN (SELECT id FROM admin_sessions ORDER BY created_at DESC LIMIT -1 OFFSET ?)').run(max);return `${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.floor(ttl/1000)}`;}
export async function clearAdminSession(request:Request){const token=cookieValue(request.headers.get('cookie')||'',COOKIE);if(token)getDb().prepare('DELETE FROM admin_sessions WHERE id=?').run(hash(token));return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;}
export function audit(eventType:string,actor:string|null,request:Request,details:Record<string,unknown>={}){getDb().prepare('INSERT INTO audit_events(created_at,event_type,actor,request_id,details) VALUES(?,?,?,?,?)').run(Date.now(),eventType,actor,request.headers.get('x-request-id'),JSON.stringify(details));}
function hash(value:string){return createHash('sha256').update(value).digest('hex');}function cookieValue(header:string,name:string){for(const part of header.split(';')){const [key,...value]=part.trim().split('=');if(key===name)return value.join('=');}return '';}function safeEqual(a:string,b:string){const left=Buffer.from(a),right=Buffer.from(b);return left.length===right.length&&timingSafeEqual(left,right);}
