import type {Generation} from '@/shared/types';
export const HISTORY_KEY='hrletter.history.v1';
export function addHistory(history:Generation[],item:Generation){return [item,...history.filter(r=>r.id!==item.id)].slice(0,30);}
export async function loadServerHistory(){const response=await fetch('/api/history',{cache:'no-store'});const data=await response.json() as {items?:Generation[];error?:string};if(!response.ok)throw new Error(data.error||'Не удалось загрузить историю с сервера.');return Array.isArray(data.items)?data.items:[];}
export async function saveServerHistory(items:Generation[]){const response=await fetch('/api/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});const data=await response.json() as {items?:Generation[];error?:string};if(!response.ok)throw new Error(data.error||'Не удалось сохранить историю на сервере.');return Array.isArray(data.items)?data.items:[];}
export async function clearServerHistory(){const response=await fetch('/api/history',{method:'DELETE'});const data=await response.json() as {items?:Generation[];error?:string};if(!response.ok)throw new Error(data.error||'Не удалось очистить историю на сервере.');}
export function exportLog(history:Generation[]){return history.map((r,i)=>`==================================================\nЗАПИСЬ №${i+1}\n==================================================\n\nДАТА\n${r.execution.startedAt}\n\nINPUT\n${JSON.stringify(r.input,null,2)}\n\nLLM\n${JSON.stringify(r.llm,null,2)}\n\nSOURCE\n${JSON.stringify(r.sources,null,2)}\n\nEXTRACTED CONTACTS\n${JSON.stringify(r.extractedContacts||{emails:[],phones:[],telegrams:[]},null,2)}\n\nCANONICAL CONTACTS\n${JSON.stringify(r.canonicalContacts||{},null,2)}\n\nCONTACT WARNINGS\n${JSON.stringify(r.contactWarnings||[],null,2)}\n\nANALYSIS\n${JSON.stringify({analysis:r.analysis,fears:r.fears,matching:r.matching,quality:r.quality},null,2)}\n\nOUTPUT\n${r.letter}\n\nПОЛНЫЙ ОТВЕТ\n${r.rawResponse}\n\nEXECUTION\n${JSON.stringify({...r.execution,statistics:r.statistics},null,2)}`).join('\n\n');}
export function downloadText(text:string,name:string){const url=URL.createObjectURL(new Blob(['\ufeff',text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function logFilename(){const d=new Date();const pad=(n:number)=>String(n).padStart(2,'0');return `cover_letter_history_${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}-${pad(d.getSeconds())}.txt`;}
